SELECT COLUMN_NAME AS emp_col, COLUMN_TYPE AS col_type FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='oa_per' AND TABLE_NAME='emp' ORDER BY ORDINAL_POSITION;
SELECT TABLE_NAME AS tbl, TABLE_ROWS AS approx_rows FROM information_schema.TABLES WHERE TABLE_SCHEMA='oa_per';
